### ISSUE TITLE
As a Student I would like to see the status of all of my submissions (draft(?), submitted, in judging, invited, not invited) so that I can verify that progress is being made on my entry’s decision.

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#10]
As a Student I would like to see the status of all of my submissions (Submitted, in judging, invited, not invited) so that I can verify that progress is being made on my entry’s decision.

- [ ] Get the shows that the Student is currently in
- [ ] Query for the entries that have been submitted
- [ ] Get the number of submissions the students have left
- [ ] When submission has ended, Show the status of each submission (pending, invited, not invited)
- [ ] Switch context out of show card(i.e if there are no submissions made vs submissions made)

**Comment by billdybas** [comment]
From our whiteboarding session:

- show the student cards for current shows or any past shows they've submitted to
- on the current show, if no submissions made, show a large submit button
- once they make a submission, show a card w/ the submission w/ a preview of the image / video and the status of the submission; include a group symbol on the card if it's a group submission; and have a plus/submit button to enter another submission
- when you submit, show a status message that was successfully submitted

**Comment by billdybas** [comment]
For future readers: we decided this story encompassed too many tasks, and we didn't finish it during our sprint, so we opted to close this story and open up smaller, more manageable stories: #186, #184, #183, #182
