### ISSUE TITLE
As a Student, I would like to be able to make a submission to an open call

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#114]
Acceptance Criteria:
- Form for what's in the schema
- Validate Fields in Frontend
- Has a success message when the student submits.

**Comment by chtinahow** [comment]
![image.png](https://images.zenhubusercontent.com/55652bb94f7a08fbb7f2f8d8/82e42409-e1e1-4f41-a843-3accd55cc675)

**Comment by billdybas** [comment]
Closed in #142
