### ISSUE TITLE
PDF Research Spike

### ISSUE THREAD

**Issue by chtinahow** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#118]

**Comment by kayladavis** [comment]
I've started to look into how we can add books as pdfs
- For upload we should be able to use multer similarly to how we use it for images
- pdfs can be rendered similarly to the endpoint for images `app.use('/pdf', express.static(__dirname + '/pdfs/file.pdf'))`
  - this can be used in chrome, edge, and firefox (as of the versions I downloaded in the past few weeks, at least)
