### ISSUE TITLE
Thumbnail Generation

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#141]
When Students upload images w/ their submission, we want to generate thumbnails of those submissions to use elsewhere in the app, so we don't have to load potentially large image files outside of the Judging interface.

We originally mentioned doing this with GraphicsMagick (https://www.npmjs.com/package/gm), however, this would require the System Administrators to have to install it on their server and maintain it – I also think GraphicsMagick or ImageMagick have had security vulnerabilities in the past. 

Alternatively, we could explore using image processing libraries built for Node – they would be installed w/ `npm install` and not need additional setup. (eg. https://github.com/oliver-moran/jimp, https://github.com/EyalAr/lwip) However, I'm skeptical of performance here – Node usually isn't the best for CPU intensive tasks.

To Research:
- thumbnail sizes
- if we need thumbnails, or if it wouldn't be an issue rendering full-size images

**Comment by chtinahow** [comment]
This includes swapping out the frontend image path for the student shows with the thumbnail path
