### ISSUE TITLE
As a student, I would like to be able to drag-and-drop the files I am uploading to my submission, so that I don’t have to navigate a file browser in my web browser for them if I already have them ready

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#15]
As a student, I would like to be able to drag-and-drop the files I am uploading to my submission, so that I don’t have to navigate a file browser in my web browser for them if I already have them ready

**Comment by billdybas** [comment]
https://react-dropzone.js.org/
