### ISSUE TITLE
As a judge, I want to be able to go right and left / forward and backward in the judging interface

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#174]
Build components that take any submission / entry component type in the center and have arrows on the left and right. Clicking the left goes to the previous submission in the shuffle order (or be greyed out is the first). Clicking on the right goes to the next submission in the shuffle order (or if this is the last (1) say "Review" - and go to the review page or (2) be greyed out) 

Additionally, #31 desires keyboard support.

**Comment by chtinahow** [comment]
This includes iterating over an array from the start to the end with entries

**Comment by chtinahow** [comment]
https://app.zenhub.com/workspace/o/robmcl4/a-b-s-t-r-a-c-t-i-o-n/issues/169
