### ISSUE TITLE
As a judge, I want to vote on videos

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#176]
This story includes making a video submission component for the Judging Interface.

This includes integrating an embed video player and displaying the appropriate one (YouTube or Vimeo) based on the URL / provider that is included in the entry. The player should take up the entire size of the component, but still be a 16:9 aspect ratio. 

The player should autoplay.

**Comment by billdybas** [comment]
See:

https://github.com/pedronauck/react-video
https://github.com/CookPete/react-player

**Comment by kayladavis** [comment]
as easy as react-video looks like it is for our case, I'm not sure it's being maintained. So I'm using react-player

**Comment by billdybas** [comment]
Ah, you're right. They still have `"react": ">=0.12.2"` listed as a `peerDependency` – that's pretty old in the React world. react-player sounds good.
