### ISSUE TITLE
As a Judge I would like to see what Shows I am assigned to that the Judging period hasn't started for yet

### ISSUE THREAD

**Issue by chtinahow** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#181]
Data submission part of the show:
Show Name
Judging Start Date
Judging End Date

Backend query change that surfaces only an active show (between entry start and judging end)
No button until judging starts
start button for when judging is happening

**Comment by kayladavis** [comment]
Acceptance Criteria: 
- Backend query change that surfaces only an active show (between entry start and judging end)
- No button until judging starts
- start button for when judging is happening
