### ISSUE TITLE
As a Student, I would like to see the judging results of my entries

### ISSUE THREAD

**Issue by chtinahow** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#184]
Acceptance Criteria:
Status bar Underneath of photos(Green Accepted, Black/Grey Not accepted)
No Make Submission Button
Entries Shown
Show Name
Submission date as "Closed"

**Comment by kayladavis** [comment]
Acceptance Criteria:
Status bar Underneath of photos(Green Accepted, Black/Grey Not accepted)
No Make Submission Button
~~Entries Shown~~ solved by rob
~~Show Name~~ solved by rob
Submission date as "Closed"
