### ISSUE TITLE
As a student I would like to submit my own photos

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#20]
JPG-only

Acceptance Criteria:

- tests
- add title:string
- add exclude from judging:Bool
- add program:string
- add year level:string
- store the properties defined in the schema
- validate:
  - dimensions positive
  - either group OR student must be present
  - every property required except comments

**Comment by kayladavis** [comment]
* add program:string
* add year level:string
Should be kicked off into another story. These are things that should go on a user, not an entry.
