### ISSUE TITLE
As an Admin, I want to be warned when I'm making invitations public so that I don't accidentally release them early

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#213]
This story involves creating the mechanism to make invitation statuses public.

This involves making a button on the top of a show's detailed view "Submission" tab that says "Make Public". When clicked, it shows a confirmation modal explaining that statuses will be made public immediately (provided judging is complete) and this is a permanent action. This modal has "Cancel" and "Make Public" buttons. "Cancel" closes the modal. "Make Public" sends a mutation to the backend setting the show's "finalized" property to "true". The modal closes, and the "Make Public" button becomes disabled (forever).

**Comment by kayladavis** [comment]
fixed in 241
