### ISSUE TITLE
As an Admin, I want a page where I can view reports and download images for a show

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#214]
This story involves designing the "Details" tab on the "View Details" show page.

This page should include a section for Reports and a section for Downloads

On the reports section, there should be links / buttons to generate each report we build.
On the downloads section, there should be a button to download the ZIP of a show's submission images

**Comment by chtinahow** [comment]
Download csv link

**Comment by chtinahow** [comment]
Put the buttons in, but not hook the generate reports just yet. Hook up the  download submissions to the button
