### ISSUE TITLE
As an Admin, I want to invite a Student's submission to a show

### ISSUE THREAD

**Issue by billdybas** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#216]
On the "Submission" tab in a show's "View Details" page, in the table of all submissions, add functionality to the "Invited?" checkbox.

When the checkbox is clicked, makes a mutation on that submission changing the invited status. Checking makes invited true. Un-checking makes invited false. Auto-saves - no need to submit any sort of form. 

Stretch Goals:
- Show a toast at the bottom of the page indicating that the invitation was saved
- Make the checkbox look like a star shape and when clicked, is filled gold

**Comment by chtinahow** [comment]
Needed update function to the backend to indicate invited status
