### ISSUE TITLE
As a Judge I would like to view a list of all open Calls to which I have been assigned so that I can continue judging submissions.

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#23]
As a Judge I would like to view a list of all open Calls to which I have been assigned so that I can continue judging submissions.

On the Judge Dashboard, create individual cards for each show a judge has been assigned to (and has been a judge in in the past?), sorted in reverse chronological order.

See whiteboard sketch for design.

Acceptance criteria:
In progress show card only
Shows the name 
Deadline
start judging Button

**Comment by chtinahow** [comment]
Don't need to show past shows

**Comment by chtinahow** [comment]
https://drive.google.com/drive/u/0/folders/0Byz-EhVky5DlbmY3eVNQUTlfRm8 Image
