### ISSUE TITLE
As a Judge, I would like to use my keyboard to indicate my voting preference, so that my voting velocity can be increased

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#30]
As a Judge, I would like to use my keyboard to indicate my voting preference, so that my voting velocity can be increased

**Comment by billdybas** [comment]
N key or 1 key for "No"
M key or 2 key for "Maybe"
Y key or 3 key for "Yes"
