### ISSUE TITLE
As an administrator I would like to be able to bulk download all invited submissions

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#54]
As an administrator I would like to be able to bulk download all invited submissions

**Comment by robmcl4** [comment]
zip file plz:

invited/stuff.jpg
not invited/stuff.jpg

**Comment by chtinahow** [comment]
For the file format:
Last name, First name, title(unless untitled then untitled1 and untitled2 etc...).jpg
