### ISSUE TITLE
As a Student, I would like to join a Group and submit as a Group, so that if I worked on art with other people, we are all recognized for our submission, and I don’t give up one of my individual submission slots for our Group submission

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#6]
As a Student, I would like to join a Group and submit as a Group, so that if I worked on art with other people, we are all recognized for our submission, and I don’t give up one of my individual submission slots for our Group submission

MVP:
- on the submission form, there's a checkbox ("I'm submitting as a group") when checked, reveals another field (students), and students enter the names of other people in the group (free-form text)

Later:
- "Add additional contributor"
- One person's dce per line
- Associate the submission with those users if they decide to log in so they can see that they're part of a group submission

**Comment by billdybas** [comment]
MVP Completed in #142
