### ISSUE TITLE
As an Administrator, I would like to assign Judges to a show call in bulk (eg. through by selecting check boxes) without having to assign them one-by-one to the call which is tedious.

### ISSUE THREAD

**Issue by robmcl4** [robmcl4/A-B-S-T-R-A-C-T-I-O-N#7]
As an Administrator, I would like to assign Judges to a show call in bulk (eg. through by selecting check boxes) without having to assign them one-by-one to the call which is tedious.

**Comment by billdybas** [comment]
Solved by #109
